services:

  backend:
    build:
      context: ./backend
    container_name: easy_market_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: easy_market
      DB_USERNAME: root
      DB_PASSWORD: root

  mysql:
    image: mysql:8.0
    container_name: easy_market_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: easy_market
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - easy_market_db:/var/lib/mysql

volumes:
  easy_market_db: